
package todphod.ui.components;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;

public class CustomerInfoPanel extends javax.swing.JPanel {
    public static int WIDTH = 965;
    public static int HEIGHT = 50;
    
    private String customerName, customerPhoneNo, customerEmail;
    private int customerId;
    
    
    /**
     * Creates new form ProductOrderPanel
     */
    public CustomerInfoPanel(int id, String customerName, String customerPhoneNo, String customerEmail) {
        initComponents();
        
        this.customerId = id;
        this.customerName = customerName;
        this.customerPhoneNo = customerPhoneNo;
        this.customerEmail = customerEmail;
        
        
        /// Initializing the labels
        this.jlCustomerName.setText(customerName);
        this.jlCustomerPhoneNo.setText(customerPhoneNo);
        this.jlCustomerEmail.setText(customerEmail);
        
        this.setSize(WIDTH, HEIGHT);
        this.setPreferredSize(new Dimension(WIDTH, HEIGHT));
        Color activeColor = new Color(68,151,255);
        Color inactiveColor = new Color(149, 160, 182);
        
       
    }

    public JLabel getJbDelete() {
        return jbDelete;
    }

    public void setJbDelete(JLabel jbDelete) {
        this.jbDelete = jbDelete;
    }

    public JLabel getJbEdit() {
        return jbEdit;
    }

    public void setJbEdit(JLabel jbEdit) {
        this.jbEdit = jbEdit;
    }

    public JLabel getJbView() {
        return jbView;
    }

    public void setJbView(JLabel jbView) {
        this.jbView = jbView;
    }
    
    public int getCustomerId() {
        return this.customerId;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCustomerName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jlCustomerPhoneNo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jlCustomerEmail = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jbEdit = new javax.swing.JLabel();
        jbView = new javax.swing.JLabel();
        jbDelete = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 253, 253));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(235, 238, 242), 1, true));
        setLayout(null);

        jlCustomerName.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlCustomerName.setForeground(new java.awt.Color(149, 160, 182));
        jlCustomerName.setText("Gaurav Punjabi");
        add(jlCustomerName);
        jlCustomerName.setBounds(20, 13, 150, 24);

        jSeparator2.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator2.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2);
        jSeparator2.setBounds(180, 0, 12, 60);

        jlCustomerPhoneNo.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlCustomerPhoneNo.setForeground(new java.awt.Color(149, 160, 182));
        jlCustomerPhoneNo.setText("882626218");
        add(jlCustomerPhoneNo);
        jlCustomerPhoneNo.setBounds(200, 10, 160, 24);

        jSeparator3.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator3.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3);
        jSeparator3.setBounds(370, 0, 12, 60);

        jlCustomerEmail.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlCustomerEmail.setForeground(new java.awt.Color(149, 160, 182));
        jlCustomerEmail.setText("gaurav.bpunjabi@gmail.com");
        add(jlCustomerEmail);
        jlCustomerEmail.setBounds(390, 10, 380, 24);

        jSeparator4.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator4.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4);
        jSeparator4.setBounds(770, 0, 12, 60);

        jbEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/data tables/edit.png"))); // NOI18N
        jbEdit.setOpaque(true);
        add(jbEdit);
        jbEdit.setBounds(800, 10, 32, 32);

        jbView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/data tables/view.png"))); // NOI18N
        jbView.setOpaque(true);
        add(jbView);
        jbView.setBounds(860, 10, 32, 32);

        jbDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/data tables/delete.png"))); // NOI18N
        jbDelete.setOpaque(true);
        add(jbDelete);
        jbDelete.setBounds(920, 10, 32, 32);
    }// </editor-fold>//GEN-END:initComponents


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jbDelete;
    private javax.swing.JLabel jbEdit;
    private javax.swing.JLabel jbView;
    private javax.swing.JLabel jlCustomerEmail;
    private javax.swing.JLabel jlCustomerName;
    private javax.swing.JLabel jlCustomerPhoneNo;
    // End of variables declaration//GEN-END:variables
}
