
package todphod.ui.components;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;
import static todphod.ui.components.CustomerInfoPanel.HEIGHT;
import static todphod.ui.components.CustomerInfoPanel.WIDTH;


public class OrderInfoPanel extends javax.swing.JPanel {
    public static int WIDTH = 965;
    public static int HEIGHT = 50;
    
    private String customerName, date, status;
    private int id, productCount;
    
    
    /**
     * Creates new form ProductOrderPanel
     */
    public OrderInfoPanel(int id, String customerName, int productCount,  String date, String status) {
        initComponents();
        
        this.id = id;
        this.customerName = customerName;
        this.date = date;
        this.status = status;
        this.productCount = productCount;
        
        /// Initializing the labels
        this.jlCustomerName.setText(customerName);
        this.jlStatus.setText(status);
        this.jlProductCount.setText(productCount  + "");
        this.jlDate.setText(date + "");
        
        this.setSize(WIDTH, HEIGHT);
        this.setPreferredSize(new Dimension(WIDTH, HEIGHT));
        Color activeColor = new Color(68,151,255);
        Color inactiveColor = new Color(149, 160, 182);
    }

    public JLabel getJbDelete() {
        return jbDelete;
    }

    public void setJbDelete(JLabel jbDelete) {
        this.jbDelete = jbDelete;
    }

    public JLabel getJbEdit() {
        return jbEdit;
    }

    public void setJbEdit(JLabel jbEdit) {
        this.jbEdit = jbEdit;
    }

    public JLabel getJbView() {
        return jbView;
    }

    public void setJbView(JLabel jbView) {
        this.jbView = jbView;
    }

    public int getId() {
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCustomerName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jlStatus = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jlProductCount = new javax.swing.JLabel();
        jbEdit = new javax.swing.JLabel();
        jbView = new javax.swing.JLabel();
        jbDelete = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jlDate = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(253, 253, 253));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(235, 238, 242), 1, true));
        setLayout(null);

        jlCustomerName.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlCustomerName.setForeground(new java.awt.Color(149, 160, 182));
        jlCustomerName.setText("Vinit");
        add(jlCustomerName);
        jlCustomerName.setBounds(20, 12, 210, 24);

        jSeparator2.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator2.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2);
        jSeparator2.setBounds(240, 0, 2, 60);

        jlStatus.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlStatus.setForeground(new java.awt.Color(149, 160, 182));
        jlStatus.setText("882626218");
        add(jlStatus);
        jlStatus.setBounds(260, 12, 200, 24);

        jSeparator3.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator3.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3);
        jSeparator3.setBounds(470, 0, 2, 60);

        jlProductCount.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlProductCount.setForeground(new java.awt.Color(149, 160, 182));
        jlProductCount.setText("1233");
        add(jlProductCount);
        jlProductCount.setBounds(490, 12, 70, 24);

        jbEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/data tables/edit.png"))); // NOI18N
        jbEdit.setOpaque(true);
        add(jbEdit);
        jbEdit.setBounds(800, 10, 32, 32);

        jbView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/data tables/view.png"))); // NOI18N
        jbView.setOpaque(true);
        add(jbView);
        jbView.setBounds(860, 10, 32, 32);

        jbDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/data tables/delete.png"))); // NOI18N
        jbDelete.setOpaque(true);
        add(jbDelete);
        jbDelete.setBounds(920, 10, 32, 32);

        jSeparator5.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator5.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator5);
        jSeparator5.setBounds(560, 0, 2, 60);

        jlDate.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlDate.setForeground(new java.awt.Color(149, 160, 182));
        jlDate.setText("5");
        add(jlDate);
        jlDate.setBounds(580, 12, 180, 24);

        jSeparator7.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator7.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator7);
        jSeparator7.setBounds(770, 0, 2, 60);
    }// </editor-fold>//GEN-END:initComponents


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel jbDelete;
    private javax.swing.JLabel jbEdit;
    private javax.swing.JLabel jbView;
    private javax.swing.JLabel jlCustomerName;
    private javax.swing.JLabel jlDate;
    private javax.swing.JLabel jlProductCount;
    private javax.swing.JLabel jlStatus;
    // End of variables declaration//GEN-END:variables
}
