
package todphod.ui.components;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;
import static todphod.ui.components.CustomerInfoPanel.HEIGHT;
import static todphod.ui.components.CustomerInfoPanel.WIDTH;


public class ProductInfoPanel extends javax.swing.JPanel {
    public static int WIDTH = 965;
    public static int HEIGHT = 50;
    
    private String categoryName, name;
    int quantity, eoqLevel, id;
    private double price;
    String setPrice;
    
    
    /**
     * Creates new form ProductOrderPanel
     */
    public ProductInfoPanel(int id, String categoryName, String name, int quantity, int eoqLevel, double price) {
        initComponents();
        
        this.id = id;
        this.categoryName = categoryName;
        this.name = name;
        this.quantity = quantity;
        this.eoqLevel = eoqLevel;
        setPrice = Double.toString(price);
        
        /// Initializing the labels
        this.jlCategoryName.setText(categoryName);
        this.jlName.setText(name);
        this.jlQuantity.setText(quantity + "");
        this.jlEoqLevel.setText(eoqLevel + "");
        this.jlName.setToolTipText(name);
        this.jlPrice.setText(setPrice);
        
        this.setSize(WIDTH, HEIGHT);
        this.setPreferredSize(new Dimension(WIDTH, HEIGHT));
        Color activeColor = new Color(68,151,255);
        Color inactiveColor = new Color(149, 160, 182);
    }

    public JLabel getJbDelete() {
        return jbDelete;
    }

    public void setJbDelete(JLabel jbDelete) {
        this.jbDelete = jbDelete;
    }

    public JLabel getJbEdit() {
        return jbEdit;
    }

    public void setJbEdit(JLabel jbEdit) {
        this.jbEdit = jbEdit;
    }

    public JLabel getJbView() {
        return jbView;
    }

    public void setJbView(JLabel jbView) {
        this.jbView = jbView;
    }

    public int getId() {
        return id;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCategoryName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jlName = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jlQuantity = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jbEdit = new javax.swing.JLabel();
        jbView = new javax.swing.JLabel();
        jbDelete = new javax.swing.JLabel();
        jlPrice = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jlEoqLevel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(253, 253, 253));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(235, 238, 242), 1, true));
        setLayout(null);

        jlCategoryName.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlCategoryName.setForeground(new java.awt.Color(149, 160, 182));
        jlCategoryName.setText("Vinit");
        add(jlCategoryName);
        jlCategoryName.setBounds(20, 12, 220, 24);

        jSeparator2.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator2.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2);
        jSeparator2.setBounds(240, 0, 2, 60);

        jlName.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlName.setForeground(new java.awt.Color(149, 160, 182));
        jlName.setText("882626218");
        add(jlName);
        jlName.setBounds(260, 12, 210, 24);

        jSeparator3.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator3.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3);
        jSeparator3.setBounds(470, 0, 2, 60);

        jlQuantity.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlQuantity.setForeground(new java.awt.Color(149, 160, 182));
        jlQuantity.setText("1233");
        add(jlQuantity);
        jlQuantity.setBounds(490, 12, 50, 24);

        jSeparator4.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator4.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator4);
        jSeparator4.setBounds(550, 0, 2, 60);

        jbEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/data tables/edit.png"))); // NOI18N
        jbEdit.setOpaque(true);
        add(jbEdit);
        jbEdit.setBounds(800, 10, 32, 32);

        jbView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/data tables/view.png"))); // NOI18N
        jbView.setOpaque(true);
        add(jbView);
        jbView.setBounds(860, 10, 32, 32);

        jbDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/data tables/delete.png"))); // NOI18N
        jbDelete.setOpaque(true);
        add(jbDelete);
        jbDelete.setBounds(920, 10, 32, 32);

        jlPrice.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlPrice.setForeground(new java.awt.Color(149, 160, 182));
        jlPrice.setText("1233.000");
        add(jlPrice);
        jlPrice.setBounds(570, 12, 100, 24);

        jSeparator5.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator5.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator5);
        jSeparator5.setBounds(680, 0, 2, 60);

        jlEoqLevel.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jlEoqLevel.setForeground(new java.awt.Color(149, 160, 182));
        jlEoqLevel.setText("5");
        add(jlEoqLevel);
        jlEoqLevel.setBounds(700, 12, 50, 24);

        jSeparator7.setBackground(new java.awt.Color(235, 238, 242));
        jSeparator7.setForeground(new java.awt.Color(235, 238, 242));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator7);
        jSeparator7.setBounds(770, 0, 2, 60);
    }// </editor-fold>//GEN-END:initComponents


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel jbDelete;
    private javax.swing.JLabel jbEdit;
    private javax.swing.JLabel jbView;
    private javax.swing.JLabel jlCategoryName;
    private javax.swing.JLabel jlEoqLevel;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlPrice;
    private javax.swing.JLabel jlQuantity;
    // End of variables declaration//GEN-END:variables
}
