
package todphod.ui.pages;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import todphod.core.Customer;
import todphod.core.Supplier;
import todphod.ui.UIUtils;
import todphod.utilities.TOClient;


public class AddCustomer extends javax.swing.JPanel {

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
        this.setSize(1090, 750);
        
        this.customInitComponents();
    }
    
    private void customInitComponents() {
        UIUtils.configureTextField(jtfCustomerName);
        UIUtils.configureTextField(jtfCustomerAddress);
        UIUtils.configureTextField(jtfCustomerPhoneNo);
        UIUtils.configureTextField(jtfCustomerEmail);
        UIUtils.configureTextField(jtfCustomerGSTNo);
        
        UIUtils.setIcon(this.jlSave, "save");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfCustomerName = new org.uikit.MaterialJTextField();
        jtfCustomerAddress = new org.uikit.MaterialJTextField();
        jtfCustomerPhoneNo = new org.uikit.MaterialJTextField();
        jtfCustomerEmail = new org.uikit.MaterialJTextField();
        jtfCustomerGSTNo = new org.uikit.MaterialJTextField();
        jlSave = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 32)); // NOI18N
        jLabel1.setText("Add Customer");

        jtfCustomerName.setLabelText("Customer Name : ");
        jtfCustomerName.setPlaceholderText("Enter the name of the customer : ");
        jtfCustomerName.setPreferredSize(new java.awt.Dimension(435, 81));

        jtfCustomerAddress.setLabelText("Customer Address : ");
        jtfCustomerAddress.setPlaceholderText("Enter the customers address : ");
        jtfCustomerAddress.setPreferredSize(new java.awt.Dimension(961, 81));

        jtfCustomerPhoneNo.setLabelText("Customer Phone No : ");
        jtfCustomerPhoneNo.setPlaceholderText("Enter the phone number : ");
        jtfCustomerPhoneNo.setPreferredSize(new java.awt.Dimension(435, 81));

        jtfCustomerEmail.setLabelText("Customer Email : ");
        jtfCustomerEmail.setPlaceholderText("Enter the email id : ");
        jtfCustomerEmail.setPreferredSize(new java.awt.Dimension(435, 81));

        jtfCustomerGSTNo.setLabelText("Customer GST NO : ");
        jtfCustomerGSTNo.setPlaceholderText("Enter the customer's GST NO : ");
        jtfCustomerGSTNo.setPreferredSize(new java.awt.Dimension(435, 81));

        jlSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/buttons/save.png"))); // NOI18N
        jlSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlSaveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlSaveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfCustomerPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jtfCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jtfCustomerGSTNo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlSave, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCustomerPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jtfCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCustomerGSTNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jlSave, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSaveMousePressed
        String name = this.jtfCustomerName.getjTextField().getText();
        String phoneNo = this.jtfCustomerPhoneNo.getjTextField().getText();
        String address = this.jtfCustomerAddress.getjTextField().getText();
        String email = this.jtfCustomerEmail.getjTextField().getText();
        String gstNo = this.jtfCustomerGSTNo.getjTextField().getText();
        String hasGst = "0";
        
        if(!phoneNo.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "The phone number should be numeric");
            return;
        } else if(phoneNo.length() != 10) {
            JOptionPane.showMessageDialog(this, "The phone number should be of 10 digits");
            return;
        } else if(!UIUtils.verifyEmail(email)) {
            JOptionPane.showMessageDialog(this, "The email is invalid.");
            return;
//        } else if((!("".equals(gstNo.length()))) && !gstNo.matches("\\d+")) {
//            JOptionPane.showMessageDialog(this, "Enter GST number");
//                //JOptionPane.showMessageDialog(this, "The GST number should be numeric");
//            return;
//        } else if(gstNo.length() != 15) {
//            JOptionPane.showMessageDialog(this, "The GST NO should be of 15 digits");
//            return;
        }
        
        if(!gstNo.isEmpty())
            hasGst = "1";
        
        Customer customer = new Customer();
        
        ArrayList<String> values = new ArrayList<>();
        values.add(name);
        values.add(phoneNo);
        values.add(address);
        values.add(email);
        values.add(hasGst);
        values.add(gstNo);
        

        int id = customer.insert(values);
        if(id != -1) {
            JOptionPane.showMessageDialog(this, "Customer Added successfully");
            TOClient.sendSMS(phoneNo, "Welcome to TodPhod. You have been added as a customer with TodPhod");
        }
    }//GEN-LAST:event_jlSaveMousePressed

    private void jlSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSaveMouseEntered
        // TODO add your handling code here:
        jlSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/buttons/save_hover.png")));
    }//GEN-LAST:event_jlSaveMouseEntered

    private void jlSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSaveMouseExited
        // TODO add your handling code here:
        jlSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendor/images/buttons/save.png")));
    }//GEN-LAST:event_jlSaveMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlSave;
    private org.uikit.MaterialJTextField jtfCustomerAddress;
    private org.uikit.MaterialJTextField jtfCustomerEmail;
    private org.uikit.MaterialJTextField jtfCustomerGSTNo;
    private org.uikit.MaterialJTextField jtfCustomerName;
    private org.uikit.MaterialJTextField jtfCustomerPhoneNo;
    // End of variables declaration//GEN-END:variables
}
