
package todphod.ui.pages;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JComponent;
import todphod.core.Customer;
import todphod.core.Order;
import todphod.core.OrderProducts;
import todphod.core.Product;
import todphod.ui.components.ItemList;
import todphod.ui.components.ProductOrderPanel;
import todphod.ui.components.ReportInfoPanel;


public class DisplayReports extends javax.swing.JPanel {

    private ItemList reportInfoList;
    private List<ReportInfoPanel> reportsPanel;
    int price;
    private double GST,totalPrice;
    /**
     * Creates new form DisplayReports
     */
    public DisplayReports() {
        initComponents();
        List<JComponent> components = this.getAllReportPanel();; 
        this.reportInfoList = new ItemList(components, ReportInfoPanel.WIDTH);
        this.reportInfoList.setBounds(55, 150, ReportInfoPanel.WIDTH, 550);
        this.add(reportInfoList);
    }

    
    private List<JComponent> getAllReportPanel() {
        Order order = new Order();
        this.reportsPanel = new ArrayList<>();
        List<JComponent> components = new ArrayList<>();
        
        Map<Integer, Order> orderMap = order.getAllOrders();
        for(Order orderInfo : orderMap.values()) {
            int id = orderInfo.getOrderID();
            if(orderInfo.getCustomerID() != 0){
            String customerName = new Customer().getCustomerByID(orderInfo.getCustomerID()).getCustomerName();
            int productCount = new OrderProducts().getAllOrderProductsByOrderID(id).keySet().size();
            double totalPrice = 0.0;
            for(OrderProducts orderProducts : new OrderProducts().getAllOrderProductsByOrderID(id).values()) {
                totalPrice += orderProducts.getQuantity() * new Product().getProductByID(orderProducts.getProductID()).getProductSellingPrice();
            }
            
            System.out.println("totalPrice = " + totalPrice);
            
            final ReportInfoPanel reportInfoPanel = new ReportInfoPanel(id, customerName, productCount, totalPrice);
            final DisplayReports displayReports = this;
            final int orderId = reportInfoPanel.getId();
            
            this.reportsPanel.add(reportInfoPanel);
            components.add(reportInfoPanel);
        }
        }
        return components;
    }
    
     private void refreshList() {
        this.remove(this.reportInfoList);
        
        List<JComponent> components = this.getAllReportPanel();
        this.reportInfoList = new ItemList(components, ReportInfoPanel.WIDTH);
        this.reportInfoList.setBounds(55, 150, ReportInfoPanel.WIDTH, 550);
        this.add(reportInfoList);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1008, 783));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Raleway", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 198, 255));
        jLabel1.setText("Reports");
        add(jLabel1);
        jLabel1.setBounds(40, 20, 200, 40);

        jLabel2.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 198, 255));
        jLabel2.setText("Customer");
        add(jLabel2);
        jLabel2.setBounds(60, 100, 120, 30);

        jLabel4.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 198, 255));
        jLabel4.setText("Qty");
        add(jLabel4);
        jLabel4.setBounds(310, 100, 40, 30);

        jLabel6.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 198, 255));
        jLabel6.setText("Price");
        add(jLabel6);
        jLabel6.setBounds(460, 100, 80, 30);

        jLabel7.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 198, 255));
        jLabel7.setText("GST");
        add(jLabel7);
        jLabel7.setBounds(640, 100, 50, 24);

        jLabel8.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 198, 255));
        jLabel8.setText("Total Amount");
        add(jLabel8);
        jLabel8.setBounds(760, 100, 150, 24);

        jLabel3.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 198, 255));
        jLabel3.setText("Export to Pdf");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3);
        jLabel3.setBounds(810, 686, 160, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new ExportToPDF();
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
