
package todphod.ui.pages;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import todphod.core.Category;
import todphod.core.Customer;
import todphod.ui.DashboardFrame;
import todphod.ui.components.CustomerInfoPanel;
import todphod.ui.components.ItemList;


public class ManageCustomers extends javax.swing.JPanel {
    private ItemList customersList;
    private List<CustomerInfoPanel> customerPanels;
    private DashboardFrame ref;
    
    /**
     * Creates new form AddCustomer
     */
    public ManageCustomers(DashboardFrame ref) {
        initComponents();
        this.setSize(1090, 750);
        this.ref = ref;
        
        List<JComponent> components = this.getAllCustomerPanels();
        
        this.customersList = new ItemList(components, CustomerInfoPanel.WIDTH);
        this.customersList.setBounds(55, 150, CustomerInfoPanel.WIDTH, 550);
        this.add(customersList);
        
        this.customInitComponents();
    }
    
    private void customInitComponents() {
        
    }
    
    private List<JComponent> getAllCustomerPanels() {
        Customer customer = new Customer();
        this.customerPanels = new ArrayList<>();
        List<JComponent> components = new ArrayList<>();
        
        Map<Integer, Customer> customerMap = customer.getAllCustomers();
        for(Customer customerInfo : customerMap.values()) {
            int id = customerInfo.getCustomerID();
            String name = customerInfo.getCustomerName();
            String phoneNo = customerInfo.getCustomerPhone();
            String email = customerInfo.getCustomerEmail();
            
            final CustomerInfoPanel customerInfoPanel = new CustomerInfoPanel(id, name, phoneNo, email);
            final ManageCustomers manageCustomers = this;
            final int customerId = customerInfoPanel.getCustomerId();
                    
            
            customerInfoPanel.getJbEdit().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                     System.out.println("Edit Pressed " + customerInfoPanel.getCustomerId());
                }
            });
            
            customerInfoPanel.getJbDelete().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                    if(JOptionPane.showConfirmDialog(manageCustomers, "Do you really want to delete the customer ?", "Delete Customer", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        Category category = new Category();
                        category.delete(customerId);
                        manageCustomers.refreshList();
                    }
                }
            });
            
            customerInfoPanel.getJbView().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                     ref.setMainPanel(new ViewCustomer(customerId));
               }
            });
            
            this.customerPanels.add(customerInfoPanel);
            components.add(customerInfoPanel);
        }
        
        return components;
    }

    private void refreshList() {
        this.remove(this.customersList);
        
        List<JComponent> components = this.getAllCustomerPanels();
        
        this.customersList = new ItemList(components, CustomerInfoPanel.WIDTH);
        this.customersList.setBounds(55, 150, CustomerInfoPanel.WIDTH, 550);
        this.add(customersList);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Raleway", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 198, 255));
        jLabel1.setText("Manage Customers");
        add(jLabel1);
        jLabel1.setBounds(55, 36, 300, 39);

        jLabel2.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 198, 255));
        jLabel2.setText("Name : ");
        add(jLabel2);
        jLabel2.setBounds(75, 120, 80, 24);

        jLabel3.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 198, 255));
        jLabel3.setText("Phone No : ");
        add(jLabel3);
        jLabel3.setBounds(255, 120, 120, 24);

        jLabel4.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 198, 255));
        jLabel4.setText("Email ID :");
        add(jLabel4);
        jLabel4.setBounds(445, 120, 120, 24);

        jLabel5.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 198, 255));
        jLabel5.setText("Controls : ");
        add(jLabel5);
        jLabel5.setBounds(855, 120, 120, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
