
package todphod.ui.pages;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import todphod.core.Category;
import todphod.core.Product;
import todphod.ui.DashboardFrame;
import todphod.ui.components.CustomerInfoPanel;
import todphod.ui.components.ItemList;
import todphod.ui.components.ProductInfoPanel;

public class ManageProducts extends javax.swing.JPanel {
    private ItemList productsList;
    private List<ProductInfoPanel> productsPanel;
    private DashboardFrame ref;
    
    /**
     * Creates new form AddCustomer
     */
    public ManageProducts(DashboardFrame ref) {
        initComponents();
        this.setSize(1090, 750);
        
        this.ref = ref;
        
        List<JComponent> components = this.getAllProductPanel();
        
        this.productsList = new ItemList(components, CustomerInfoPanel.WIDTH);
        this.productsList.setBounds(55, 150, CustomerInfoPanel.WIDTH, 550);
        this.add(productsList);
        
        this.customInitComponents();
    }
    
    private void customInitComponents() {
        
    }
    
    private List<JComponent> getAllProductPanel() {
        Product product = new Product();
        this.productsPanel = new ArrayList<>();
        List<JComponent> components = new ArrayList<>();
        
        Map<Integer, Product> productMap = product.getAllProducts();
        
        for(Product productInfo : productMap.values()) {
            int id = productInfo.getProductID();
            String name = productInfo.getProductName();
            String categoryName = new Category().getCategoryByID(productInfo.getCategoryID()).getCategoryName();
            int quantity = productInfo.getProductQuantity();
            int eoqLevel = productInfo.getProductEOQLevel();
            double price = productInfo.getProductSellingPrice();
            
            
            double GST = ((quantity * price)/ 9.3);
            
            
            
            String size = productInfo.getProductAdditionalSpecification();
            
            final ProductInfoPanel productInfoPanel = new ProductInfoPanel(id, categoryName, name, quantity, eoqLevel,price);
            final int productId = productInfoPanel.getId();
            final ManageProducts manageProducts = this;
            
            productInfoPanel.getJbEdit().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                     System.out.println("Edit Pressed " + productInfoPanel.getId());
               }
            });
            
            productInfoPanel.getJbDelete().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                    if(JOptionPane.showConfirmDialog(manageProducts, "Do you really want to delete the product ?", "Delete Products", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        Product product = new Product();
                        product.delete(productId);
                        manageProducts.refreshList();
                    }
               }
            });
            
            productInfoPanel.getJbView().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                    ref.setMainPanel(new ViewProduct(productId));
               }
            });
            
            this.productsPanel.add(productInfoPanel);
            components.add(productInfoPanel);
        }
        
        return components;
    }

    private void refreshList() {
        this.remove(this.productsList);
        
        List<JComponent> components = this.getAllProductPanel();
        
        this.productsList = new ItemList(components, CustomerInfoPanel.WIDTH);
        this.productsList.setBounds(55, 150, CustomerInfoPanel.WIDTH, 550);
        this.add(productsList);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Raleway", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 198, 255));
        jLabel1.setText("Manage Products");
        add(jLabel1);
        jLabel1.setBounds(55, 36, 300, 39);

        jLabel2.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 198, 255));
        jLabel2.setText("Category  ");
        add(jLabel2);
        jLabel2.setBounds(75, 120, 100, 24);

        jLabel5.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 198, 255));
        jLabel5.setText("Controls : ");
        add(jLabel5);
        jLabel5.setBounds(855, 120, 120, 24);

        jLabel3.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 198, 255));
        jLabel3.setText("Qty");
        add(jLabel3);
        jLabel3.setBounds(545, 120, 40, 24);

        jLabel4.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 198, 255));
        jLabel4.setText("Name ");
        add(jLabel4);
        jLabel4.setBounds(315, 120, 80, 24);

        jLabel6.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 198, 255));
        jLabel6.setText("Price");
        add(jLabel6);
        jLabel6.setBounds(625, 120, 60, 24);

        jLabel7.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 198, 255));
        jLabel7.setText("EOQ");
        add(jLabel7);
        jLabel7.setBounds(755, 120, 60, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
