
package todphod.ui.pages;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import todphod.core.Category;
import todphod.ui.DashboardFrame;
import todphod.ui.components.CategoryInfoPanel;
import todphod.ui.components.CustomerInfoPanel;
import todphod.ui.components.ItemList;

public class ManageCategories extends javax.swing.JPanel {
    private ItemList categoriesList;
    private List<CategoryInfoPanel> productsPanel;
    private DashboardFrame ref;
    
    /**
     * Creates new form AddCustomer
     */
    public ManageCategories(DashboardFrame dashboardFrame) {
        initComponents();
        this.setSize(1090, 750);
        this.ref = dashboardFrame;
        
        List<JComponent> components = this.getAllCategoriesPanel();
        
        this.categoriesList = new ItemList(components, CustomerInfoPanel.WIDTH);
        this.categoriesList.setBounds(55, 150, CustomerInfoPanel.WIDTH, 550);
        this.add(categoriesList);
        
        this.customInitComponents();
    }
    
    private void customInitComponents() {
        
    }
    
    private List<JComponent> getAllCategoriesPanel() {
        Category category = new Category();
        this.productsPanel = new ArrayList<>();
        List<JComponent> components = new ArrayList<>();
        
        Map<Integer, Category> categoryMap = category.getAllCategories();
        for(Category categoryInfo : categoryMap.values()) {
            int id = categoryInfo.getCategoryID();
            String name = categoryInfo.getCategoryName();
            
            final CategoryInfoPanel productInfoPanel = new CategoryInfoPanel(id, name);
            final int categoryId = productInfoPanel.getCategoryId();
            final ManageCategories manageCategories = this;
            
            productInfoPanel.getJbEdit().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                     System.out.println("Edit Pressed " + productInfoPanel.getCategoryId());
               }
            });
            productInfoPanel.getJbDelete().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                    if(JOptionPane.showConfirmDialog(manageCategories, "Do you really want to delete the category ?", "Delete Categories", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        Category category = new Category();
                        category.delete(categoryId);
                        manageCategories.refreshList();
                    }
               }
            });
            
            productInfoPanel.getJbView().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                    ref.setMainPanel(new ViewCategory(categoryId));
                }
            });
            
            this.productsPanel.add(productInfoPanel);
            components.add(productInfoPanel);
        }
        
        return components;
    }
    
    private void refreshList() {
        this.remove(this.categoriesList);
        List<JComponent> components = this.getAllCategoriesPanel();
        this.categoriesList = new ItemList(components, CustomerInfoPanel.WIDTH);
        this.categoriesList.setBounds(55, 150, CustomerInfoPanel.WIDTH, 550);
        this.add(categoriesList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Raleway", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 198, 255));
        jLabel1.setText("Manage Categories");
        add(jLabel1);
        jLabel1.setBounds(55, 36, 300, 39);

        jLabel2.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 198, 255));
        jLabel2.setText("Name : ");
        add(jLabel2);
        jLabel2.setBounds(75, 120, 80, 24);

        jLabel5.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 198, 255));
        jLabel5.setText("Controls : ");
        add(jLabel5);
        jLabel5.setBounds(855, 120, 120, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
