
package todphod.ui.pages;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import todphod.core.Product;
import todphod.core.Purchase;
import todphod.core.Supplier;
import todphod.ui.components.CustomerInfoPanel;
import todphod.ui.components.ItemList;
import todphod.ui.components.PurchaseInfoPanel;


public class ManagePurchases extends javax.swing.JPanel {
    private ItemList purchaseList;
    private List<PurchaseInfoPanel> purchasePanels;
    
    
    /**
     * Creates new form AddCustomer
     */
    public ManagePurchases() {
        initComponents();
        this.setSize(1090, 750);
        
        List<JComponent> components = this.getAllPurchasePanels();
        
        this.purchaseList = new ItemList(components, CustomerInfoPanel.WIDTH);
        this.purchaseList.setBounds(55, 150, CustomerInfoPanel.WIDTH, 550);
        this.purchaseList.setPreferredSize(new Dimension(CustomerInfoPanel.WIDTH, 550));
        this.add(purchaseList);
        
        
        this.customInitComponents();
    }
    
    private void customInitComponents() {
        
    }
    
    private List<JComponent> getAllPurchasePanels() {
        Purchase purchase = new Purchase();
        this.purchasePanels = new ArrayList<>();
        List<JComponent> components = new ArrayList<>();
        
        Map<Integer, Purchase> purchaseMap = purchase.getAllPurchases();
        for(Purchase purchaseInfo : purchaseMap.values()) {
            int id = purchaseInfo.getPurchaseID();
            String supplier = new Supplier().getSupplierByID(purchaseInfo.getSupplierID()).getSupplierName();
            String product = new Product().getProductByID(purchaseInfo.getProductID()).getProductName();
            double rate = purchaseInfo.getPurchaseRate();
            
            final PurchaseInfoPanel purchaseInfoPanel = new PurchaseInfoPanel(id, supplier, product, id, rate);
            final int purchaseId = purchaseInfoPanel.getId();
            
            purchaseInfoPanel.getJbEdit().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                     System.out.println("Edit Pressed " + purchaseInfoPanel.getId());
               }
            });
            
            final ManagePurchases managePurchases = this;
            
            purchaseInfoPanel.getJbDelete().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                    if(JOptionPane.showConfirmDialog(managePurchases, "Do you really want to delete the purchase ?", "Delete Purchase", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        Purchase purchase = new Purchase();
                        purchase.delete(purchaseId);
                        managePurchases.refreshList();
                    }
               }
            });
            
            purchaseInfoPanel.getJbView().addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent mouseEvent) {
                     System.out.println("View Pressed");
               }
            });
            
            this.purchasePanels.add(purchaseInfoPanel);
            components.add(purchaseInfoPanel);
        }
        
        return components;
    }
    
    private void refreshList() {
        this.remove(purchaseList);
        List<JComponent> components = this.getAllPurchasePanels();
        this.purchaseList = new ItemList(components, CustomerInfoPanel.WIDTH);
        this.purchaseList.setBounds(55, 150, CustomerInfoPanel.WIDTH, 550);
        this.purchaseList.setPreferredSize(new Dimension(CustomerInfoPanel.WIDTH, 550));
        this.add(purchaseList);
        
        this.validate();
        this.purchaseList.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Raleway", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 198, 255));
        jLabel1.setText("Manage Purchases");
        add(jLabel1);
        jLabel1.setBounds(55, 36, 300, 39);

        jLabel2.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 198, 255));
        jLabel2.setText("Supplier : ");
        add(jLabel2);
        jLabel2.setBounds(75, 120, 130, 24);

        jLabel3.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 198, 255));
        jLabel3.setText("Product : ");
        add(jLabel3);
        jLabel3.setBounds(315, 120, 120, 24);

        jLabel4.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 198, 255));
        jLabel4.setText("Quantity : ");
        add(jLabel4);
        jLabel4.setBounds(545, 120, 120, 24);

        jLabel5.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 198, 255));
        jLabel5.setText("Controls : ");
        add(jLabel5);
        jLabel5.setBounds(855, 120, 120, 24);

        jLabel6.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 198, 255));
        jLabel6.setText("Rate : ");
        add(jLabel6);
        jLabel6.setBounds(685, 120, 120, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
