
package todphod.ui.pages;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import todphod.core.Customer;
import todphod.ui.UIUtils;

public class ViewCustomer extends javax.swing.JPanel {

    /**
     * Creates new form AddCustomer
     */
    public ViewCustomer(int customerId) {
        initComponents();
        this.setSize(1090, 750);
        
        Customer customer = new Customer().getCustomerByID(customerId);
        this.jtfCustomerAddress.getjTextField().setText(customer.getCustomerAddress());
        this.jtfCustomerEmail.getjTextField().setText(customer.getCustomerEmail());;
        this.jtfCustomerGSTNo.getjTextField().setText(customer.getCustomerGSTNo());
        this.jtfCustomerName.getjTextField().setText(customer.getCustomerName());
        this.jtfCustomerPhoneNo.getjTextField().setText(customer.getCustomerPhone());
        
        this.jtfCustomerAddress.getjTextField().setEnabled(false);
        this.jtfCustomerEmail.getjTextField().setEnabled(false);
        this.jtfCustomerGSTNo.getjTextField().setEnabled(false);
        this.jtfCustomerName.getjTextField().setEnabled(false);
        this.jtfCustomerPhoneNo.getjTextField().setEnabled(false);
        
        this.customInitComponents();
    }
    
    private void customInitComponents() {
        UIUtils.configureTextField(jtfCustomerName);
        UIUtils.configureTextField(jtfCustomerAddress);
        UIUtils.configureTextField(jtfCustomerPhoneNo);
        UIUtils.configureTextField(jtfCustomerEmail);
        UIUtils.configureTextField(jtfCustomerGSTNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfCustomerName = new org.uikit.MaterialJTextField();
        jtfCustomerAddress = new org.uikit.MaterialJTextField();
        jtfCustomerPhoneNo = new org.uikit.MaterialJTextField();
        jtfCustomerEmail = new org.uikit.MaterialJTextField();
        jtfCustomerGSTNo = new org.uikit.MaterialJTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 32)); // NOI18N
        jLabel1.setText("View Customer");

        jtfCustomerName.setLabelText("Customer Name : ");
        jtfCustomerName.setPlaceholderText("Enter the name of the customer : ");
        jtfCustomerName.setPreferredSize(new java.awt.Dimension(435, 81));

        jtfCustomerAddress.setLabelText("Customer Address : ");
        jtfCustomerAddress.setPlaceholderText("Enter the customers address : ");
        jtfCustomerAddress.setPreferredSize(new java.awt.Dimension(961, 81));

        jtfCustomerPhoneNo.setLabelText("Customer Phone No : ");
        jtfCustomerPhoneNo.setPlaceholderText("Enter the phone number : ");
        jtfCustomerPhoneNo.setPreferredSize(new java.awt.Dimension(435, 81));

        jtfCustomerEmail.setLabelText("Customer Email : ");
        jtfCustomerEmail.setPlaceholderText("Enter the email id : ");
        jtfCustomerEmail.setPreferredSize(new java.awt.Dimension(435, 81));

        jtfCustomerGSTNo.setLabelText("Customer GST NO : ");
        jtfCustomerGSTNo.setPlaceholderText("Enter the customer's GST NO : ");
        jtfCustomerGSTNo.setPreferredSize(new java.awt.Dimension(435, 81));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfCustomerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfCustomerPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jtfCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jtfCustomerGSTNo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCustomerPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jtfCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCustomerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCustomerGSTNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private org.uikit.MaterialJTextField jtfCustomerAddress;
    private org.uikit.MaterialJTextField jtfCustomerEmail;
    private org.uikit.MaterialJTextField jtfCustomerGSTNo;
    private org.uikit.MaterialJTextField jtfCustomerName;
    private org.uikit.MaterialJTextField jtfCustomerPhoneNo;
    // End of variables declaration//GEN-END:variables
}
