
package todphod.ui.pages;

import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.swing.AutoCompleteSupport;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.coobird.thumbnailator.Thumbnailator;
import todphod.core.Category;
import todphod.core.ImageUtils;
import todphod.core.Product;
import todphod.ui.UIUtils;



public class ViewProduct extends javax.swing.JPanel {
    private Map<String, Integer> categories;
    private BufferedImage bufferedImage;
    
    /**
     * Creates new form AddCustomer
     */
    public ViewProduct(int productId) {
        initComponents();
        this.setSize(1090, 750);
        
//        this.getAllCategories();
        this.customInitComponents();
        
        
        Product product = new Product().getProductByID(productId);
//        this.jcbCategories.add(new Category().getCategoryByID(product.getCategoryID()).getCategoryName());
        this.jtfProductName.getjTextField().setText(product.getProductName());
        this.jtfProductEOQLevel.getjTextField().setText(product.getProductEOQLevel() + "");
        this.jtfProductQuantity.getjTextField().setText(product.getProductQuantity() + "");
        this.jtfProductSize.getjTextField().setText(product.getProductAdditionalSpecification());
        this.jtfProductSellingPrice.getjTextField().setText(product.getProductSellingPrice() + "");
        this.jlImage.setIcon(new ImageIcon(ImageUtils.toImage(product.getProductImage())));
        
        this.jtfProductName.getjTextField().setEnabled(false);
        this.jtfProductEOQLevel.getjTextField().setEnabled(false);
        this.jtfProductQuantity.getjTextField().setEnabled(false);
        this.jtfProductSize.getjTextField().setEnabled(false);
        this.jtfProductSellingPrice.getjTextField().setEnabled(false);
        this.jcbCategories.setEnabled(false);
    }
    
    private void getAllCategories() {
        this.categories = new HashMap<>();
        Category category = new Category();
        Map<Integer, Category> categoryMap = category.getAllCategories();
        
        String categories[] = new String[categoryMap.keySet().size()];
        int index = 0;
        for(Map.Entry<Integer, Category> categoryEntry : categoryMap.entrySet()) {
            String name = categoryEntry.getValue().getCategoryName();
            int id = categoryEntry.getKey();
            
            categories[index++] = name;
            this.categories.put(name, id);
        }
        
        AutoCompleteSupport.install(this.jcbCategories, GlazedLists.eventListOf(categories));
    }
    
    private void customInitComponents() {
        UIUtils.configureTextField(jtfProductSellingPrice);
        UIUtils.configureTextField(jtfProductQuantity);
        UIUtils.configureTextField(jtfProductName);
        UIUtils.configureTextField(jtfProductEOQLevel);
        UIUtils.configureTextField(jtfProductSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfProductQuantity = new org.uikit.MaterialJTextField();
        jtfProductName = new org.uikit.MaterialJTextField();
        jtfProductEOQLevel = new org.uikit.MaterialJTextField();
        jtfProductSize = new org.uikit.MaterialJTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbCategories = new org.uikit.KeyValueJComboBox();
        jtfProductSellingPrice = new org.uikit.MaterialJTextField();
        jlImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 32)); // NOI18N
        jLabel1.setText("View Product");

        jtfProductQuantity.setLabelText("Product Quantity : ");
        jtfProductQuantity.setPlaceholderText("Enter the product quantity : ");
        jtfProductQuantity.setPreferredSize(new java.awt.Dimension(961, 81));

        jtfProductName.setLabelText("Product Name : ");
        jtfProductName.setPlaceholderText("Enter the product name : ");
        jtfProductName.setPreferredSize(new java.awt.Dimension(435, 81));

        jtfProductEOQLevel.setLabelText("Product EOQ Level : ");
        jtfProductEOQLevel.setPlaceholderText("Enter the product EOQ Level : ");
        jtfProductEOQLevel.setPreferredSize(new java.awt.Dimension(435, 81));

        jtfProductSize.setLabelText("Product Size : ");
        jtfProductSize.setPlaceholderText("Enter the product's size : ");
        jtfProductSize.setPreferredSize(new java.awt.Dimension(435, 81));

        jLabel3.setFont(new java.awt.Font("Raleway", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(149, 160, 182));
        jLabel3.setText("Select Category of Product : ");

        jtfProductSellingPrice.setLabelText("Product Selling Price : ");
        jtfProductSellingPrice.setPlaceholderText("Enter the product selling price : ");

        jlImage.setBackground(new java.awt.Color(187, 187, 187));
        jlImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlImage.setText("Select a image");
        jlImage.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jtfProductEOQLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jtfProductSize, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfProductQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbCategories, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(jtfProductSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jcbCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfProductSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfProductEOQLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfProductSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private org.uikit.KeyValueJComboBox jcbCategories;
    private javax.swing.JLabel jlImage;
    private org.uikit.MaterialJTextField jtfProductEOQLevel;
    private org.uikit.MaterialJTextField jtfProductName;
    private org.uikit.MaterialJTextField jtfProductQuantity;
    private org.uikit.MaterialJTextField jtfProductSellingPrice;
    private org.uikit.MaterialJTextField jtfProductSize;
    // End of variables declaration//GEN-END:variables
}
